version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: github.com/emersion/go-imap/v2
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

